export const eventTypes = {
  APP_LAUNCH: 'app_launch',
  APP_CLOSE: 'app_close',
  USER_LOGIN: 'user_login',
  USER_LOGOUT: 'user_logout',
  USER_SIGNUP: 'user_signup',
  USER_PROFILE_UPDATE: 'user_profile_update',
  USER_PASSWORD_RESET: 'user_password_reset',
  USER_PASSWORD_CHANGE: 'user_password_change',
  BUTTON_CLICK: 'button_click',
  SCREEN_VIEW: 'screen_view',
  DATA_ACQUISITION: 'data_acquisition',
  ERROR: 'error',
  PURCHASE: 'purchase',
  SHARE: 'share',
  CUSTOM_EVENT: 'custom_event',
  NOTIFICATION_RECEIVED: 'notification_received',
  NOTIFICATION_OPENED: 'notification_opened',
  FILE_DOWNLOAD: 'file_download',
}