export const astroDataInfosTranslations = {
  dso: {
    title: "Deep Sky Objects",
    text1: "All data related to deep sky objects comes from a custom database built from the following catalogs:",
  },
  stars: {
    title: "Stars",
    text1: "All data related to stars comes from an export of the SIMBAD database made in July 2024",
  },
  planets: {
    title: "Planets",
    text1: "All data related to planets is the result of internal astronomical calculations in the application made with the help of an independent tool: Observerly",
  },
  satellites: {
    title: "Satellites",
    iss: {
      title: "International Space Station (ISS)",
      text1: "All data related to the ISS comes from the 'Where The Iss At (WTIA)' API, which provides aggregated real-time formatted data about the ISS.",
      text2: "WTIA uses data from NASA, Space-track.com, and CelesTrak.com to provide accurate information on the position of the ISS.",
    },
    starlink: {
      title: "Starlink",
      text1: "Data used to visualize the positioning of Starlink satellites comes from the API: starlinkapi (NPM)",
      text2: "Data on Starlink satellite launches comes from the API: Launch Library 2 (The Space Devs)",
    }
  },
  launchData: {
    title: "Rocket Launch Data",
    text1: "All rocket launch data is retrieved in real time from the API: Launch Library 2 (The Space Devs)"
  },
  solarWeather: {
    title: "Solar Weather",
    text1: "All data related to solar weather comes from the following websites:",
    text2: "- Solar Dynamics Observatory (sdo.gsfc.nasa.gov)\n- Solar and Heliospheric Observatory (soho.nascom.nasa.gov)\n- National Oceanic and Atmospheric Administration (noaa.gov)"
  },
  apod: {
    title: "Astronomy Picture of the Day (APOD)",
    text1: "The images and texts in the Astronomy Picture of the Day feature come from the official NASA API: Astronomy Picture of the Day (APOD).",
  },
  skymap: {
    title: "Sky Maps",
    text1: "The sky maps generated by the application are produced from internal calculations using the independent tool: Observerly",
  },
  moonPhases: {
    title: "Moon Phases",
    text1: "The information and lunar phases displayed in the application are calculated internally using the independent tool: Observerly",
  },
  conjunctions: {
    title: "Planetary Conjunctions",
    text1: "The information on planetary conjunctions displayed is calculated internally using the independent tool: Observerly",
  },
  eclipses: {
    title: "Solar and Lunar Eclipses",
    text1: "The information on eclipses displayed in the application is calculated using the IMCCE API (Institut de Mécanique Céleste et de Calcul des Éphémérides)",
  }
}