export const astroDataInfosTranslations = {
  dso: {
    title: "Deep Sky Objects",
    text1: "All data related to deep sky objects comes from a custom database, created from data from the following catalogs:",
  },
  stars: {
    title: "Stars",
    text1: "All data related to stars comes from an export of the SIMBAD database made in July 2024",
  },
  planets: {
    title: "Planets",
    text1: "All data related to planets is the result of astronomical calculations made with the help of an independent tool: Observerly",
  },
  launchData: {
    title: "Rocket Launch Data",
    text1: "All rocket launch data is retrieved in real time from the API: Launch Library 2 (The Space Devs)"
  },
  satellites: {
    title: "Satellites",
    iss: {
      title: "International Space Station (ISS)",
      text1: "All data related to the ISS comes from the 'Where The Iss At (WTIA)' API, which provides real-time formatted data on the ISS.",
      text2: "WTIA uses data from NASA, Space-track.com, and CelesTrack.com to provide accurate information on the position of the ISS.",
    },
    starlink: {
      title: "Starlink",
      text1: "Data related to the visualization of the positioning of Starlink satellites comes from the API: starlinkapi (NPM)",
      text2: "Data on Starlink satellite launches comes from the API: Launch Library 2 (The Space Devs)"
    }
  },
  solarWeather: {
    title: "Solar Weather",
    text1: "All data related to solar weather comes from the following websites:",
  },
  apod: {
    title: "Astronomy Picture of the Day (APOD)",
    text1: "The images and texts in the Astronomy Picture of the Day feature come from the official NASA API: Astronomy Picture of the Day (APOD).",
  },
  skymap: {
    title: "Sky Maps",
    text1: "The sky maps generated by the application are created from calculations made using the independent tool: Observerly",
  },
  moonPhases: {
    title: "Moon Phases",
    text1: "The informations and moon phases displayed in the application are calculated using the independent tool: Observerly",
  }
}