import { andromeda, aquarius, aquila, bootes, camelopardalis, canesVenatici, capricornus, cassiopeia, cepheus, comaBerenices, coronaAustralis, coronaBorealis, cygnus, delphinus, draco, equuleus, hercules, lacerta, leo, leoMinor, libra, lynx, lyra } from "@observerly/astrometry";

export const constellationsAsterisms = [
  hercules.features[0].geometry.coordinates,
  draco.features[0].geometry.coordinates,
  cepheus.features[0].geometry.coordinates,
  aquila.features[0].geometry.coordinates,
  cygnus.features[0].geometry.coordinates,
  leo.features[0].geometry.coordinates,
  leoMinor.features[0].geometry.coordinates,
  lynx.features[0].geometry.coordinates,
  lyra.features[0].geometry.coordinates,
  libra.features[0].geometry.coordinates,
  andromeda.features[0].geometry.coordinates,
  lacerta.features[0].geometry.coordinates,
  aquarius.features[0].geometry.coordinates,
  capricornus.features[0].geometry.coordinates,
  cassiopeia.features[0].geometry.coordinates,
  comaBerenices.features[0].geometry.coordinates,
  bootes.features[0].geometry.coordinates,
  coronaAustralis.features[0].geometry.coordinates,
  camelopardalis.features[0].geometry.coordinates,
  canesVenatici.features[0].geometry.coordinates,
  coronaBorealis.features[0].geometry.coordinates,
  delphinus.features[0].geometry.coordinates,
  equuleus.features[0].geometry.coordinates,
]