// @ts-ignore
import {andromeda, constellations} from  "@observerly/astrometry/dist/constellations";

export const constellationsAsterisms = [
  constellations.get("Andromeda"),
  constellations.get("Antila"),
  constellations.get("Apus"),
  constellations.get("Aquarius"),
  constellations.get("Aquila"),
  constellations.get("Ara"),
  constellations.get("Aries"),
  constellations.get("Auriga"),
  constellations.get("Boötes"),
  constellations.get("Caelum"),
  constellations.get("Camelopardalis"),
  constellations.get("Cancer"),
  constellations.get("Canes Venatici"),
  constellations.get("Canis Major"),
  constellations.get("Canis Minor"),
  constellations.get("Capricornus"),
  constellations.get("Carina"),
  constellations.get("Cassiopeia"),
  constellations.get("Centaurus"),
  constellations.get("Cepheus"),
  constellations.get("Cetus"),
  constellations.get("Chamaeleon"),
  constellations.get("Circinus"),
  constellations.get("Columba"),
  constellations.get("Coma Berenices"),
  constellations.get("Corona Australis"),
  constellations.get("Corona Borealis"),
  constellations.get("Corvus"),
  constellations.get("Crater"),
  constellations.get("Crux"),
  constellations.get("Cygnus"),
  constellations.get("Delphinus"),
  constellations.get("Dorado"),
  constellations.get("Draco"),
  constellations.get("Equuleus"),
  constellations.get("Eridanus"),
  constellations.get("Fornax"),
  constellations.get("Gemini"),
  constellations.get("Grus"),
  constellations.get("Hercules"),
  constellations.get("Horologium"),
  constellations.get("Hydra"),
  constellations.get("Hydrus"),
  constellations.get("Indus"),
  constellations.get("Lacerta"),
  constellations.get("Leo"),
  constellations.get("Leo Minor"),
  constellations.get("Lepus"),
  constellations.get("Libra"),
  constellations.get("Lupus"),
  constellations.get("Lynx"),
  constellations.get("Lyra"),
  constellations.get("Mensa"),
  constellations.get("Microscopium"),
  constellations.get("Monoceros"),
  constellations.get("Musca"),
  constellations.get("Norma"),
  constellations.get("Octans"),
  constellations.get("Ophiuchus"),
  constellations.get("Orion"),
  constellations.get("Pavo"),
  constellations.get("Pegasus"),
  constellations.get("Perseus"),
  constellations.get("Phoenix"),
  constellations.get("Pictor"),
  constellations.get("Pisces"),
  constellations.get("Piscis Austrinus"),
  constellations.get("Puppis"),
  constellations.get("Pyxis"),
  constellations.get("Reticulum"),
  constellations.get("Sagitta"),
  constellations.get("Sagittarius"),
  constellations.get("Scorpius"),
  constellations.get("Sculptor"),
  constellations.get("Scutum"),
  constellations.get("Serpens Caput"),
  constellations.get("Serpens Cauda"),
  constellations.get("Sextans"),
  constellations.get("Taurus"),
  constellations.get("Telescopium"),
  constellations.get("Triangulum"),
  constellations.get("Triangulum Australe"),
  constellations.get("Tucana"),
  constellations.get("Ursa Major"),
  constellations.get("Ursa Minor"),
  constellations.get("Vela"),
  constellations.get("Virgo"),
  constellations.get("Volans"),
  constellations.get("Vulpecula"),
]