import { i18n } from "./i18n";

export const getConstellationName = (constellation: string) => {
  switch (constellation) {
    case 'And':
      return i18n.t('constellations.And');
    case 'Ant':
      return i18n.t('constellations.Ant');
    case 'Aps':
      return i18n.t('constellations.Aps');
    case 'Aql':
      return i18n.t('constellations.Aql');
    case 'Aqr':
      return i18n.t('constellations.Aqr');
    case 'Ara':
      return i18n.t('constellations.Ara');
    case 'Ari':
      return i18n.t('constellations.Ari');
    case 'Aur':
      return i18n.t('constellations.Aur');
    case 'Boo':
      return i18n.t('constellations.Boo');
    case 'Cae':
      return i18n.t('constellations.Cae');
    case 'Cam':
      return i18n.t('constellations.Cam');
    case 'Cap':
      return i18n.t('constellations.Cap');
    case 'Car':
      return i18n.t('constellations.Car');
    case 'Cas':
      return i18n.t('constellations.Cas');
    case 'Cen':
      return i18n.t('constellations.Cen');
    case 'Cep':
      return i18n.t('constellations.Cep');
    case 'Cet':
      return i18n.t('constellations.Cet');
    case 'Cha':
      return i18n.t('constellations.Cha');
    case 'Cir':
      return i18n.t('constellations.Cir');
    case 'CMa':
      return i18n.t('constellations.CMa');
    case 'CMi':
      return i18n.t('constellations.CMi');
    case 'Cnc':
      return i18n.t('constellations.Cnc');
    case 'Col':
      return i18n.t('constellations.Col');
    case 'Com':
      return i18n.t('constellations.Com');
    case 'CrA':
      return i18n.t('constellations.CrA');
    case 'CrB':
      return i18n.t('constellations.CrB');
    case 'Crt':
      return i18n.t('constellations.Crt');
    case 'Cru':
      return i18n.t('constellations.Cru');
    case 'Crv':
      return i18n.t('constellations.Crv');
    case 'CVn':
      return i18n.t('constellations.CVn');
    case 'Cyg':
      return i18n.t('constellations.Cyg');
    case 'Del':
      return i18n.t('constellations.Del');
    case 'Dor':
      return i18n.t('constellations.Dor');
    case 'Dra':
      return i18n.t('constellations.Dra');
    case 'Equ':
      return i18n.t('constellations.Equ');
    case 'Eri':
      return i18n.t('constellations.Eri');
    case 'For':
      return i18n.t('constellations.For');
    case 'Gem':
      return i18n.t('constellations.Gem');
    case 'Gru':
      return i18n.t('constellations.Gru');
    case 'Her':
      return i18n.t('constellations.Her');
    case 'Hor':
      return i18n.t('constellations.Hor');
    case 'Hya':
      return i18n.t('constellations.Hya');
    case 'Hyi':
      return i18n.t('constellations.Hyi');
    case 'Ind':
      return i18n.t('constellations.Ind');
    case 'Lac':
      return i18n.t('constellations.Lac');
    case 'Leo':
      return i18n.t('constellations.Leo');
    case 'Lep':
      return i18n.t('constellations.Lep');
    case 'Lib':
      return i18n.t('constellations.Lib');
    case 'LMi':
      return i18n.t('constellations.LMi');
    case 'Lup':
      return i18n.t('constellations.Lup');
    case 'Lyn':
      return i18n.t('constellations.Lyn');
    case 'Lyr':
      return i18n.t('constellations.Lyr');
    case 'Men':
      return i18n.t('constellations.Men');
    case 'Mic':
      return i18n.t('constellations.Mic');
    case 'Mon':
      return i18n.t('constellations.Mon');
    case 'Mus':
      return i18n.t('constellations.Mus');
    case 'Nor':
      return i18n.t('constellations.Nor');
    case 'Oct':
      return i18n.t('constellations.Oct');
    case 'Oph':
      return i18n.t('constellations.Oph');
    case 'Ori':
      return i18n.t('constellations.Ori');
    case 'Pav':
      return i18n.t('constellations.Pav');
    case 'Peg':
      return i18n.t('constellations.Peg');
    case 'Per':
      return i18n.t('constellations.Per');
    case 'Phe':
      return i18n.t('constellations.Phe');
    case 'Pic':
      return i18n.t('constellations.Pic');
    case 'PsA':
      return i18n.t('constellations.PsA');
    case 'Psc':
      return i18n.t('constellations.Psc');
    case 'Pup':
      return i18n.t('constellations.Pup');
    case 'Pyx':
      return i18n.t('constellations.Pyx');
    case 'Ret':
      return i18n.t('constellations.Ret');
    case 'Scl':
      return i18n.t('constellations.Scl');
    case 'Sco':
      return i18n.t('constellations.Sco');
    case 'Sct':
      return i18n.t('constellations.Sct');
    case 'Ser':
      return i18n.t('constellations.Ser');
    case 'Se1':
      return i18n.t('constellations.Se1');
    case 'Se2':
      return i18n.t('constellations.Se2');
    case 'Sex':
      return i18n.t('constellations.Sex');
    case 'Sge':
      return i18n.t('constellations.Sge');
    case 'Sgr':
      return i18n.t('constellations.Sgr');
    case 'Tau':
      return i18n.t('constellations.Tau');
    case 'Tel':
      return i18n.t('constellations.Tel');
    case 'TrA':
      return i18n.t('constellations.TrA');
    case 'Tri':
      return i18n.t('constellations.Tri');
    case 'Tuc':
      return i18n.t('constellations.Tuc');
    case 'UMa':
      return i18n.t('constellations.UMa');
    case 'UMi':
      return i18n.t('constellations.UMi');
    case 'Vel':
      return i18n.t('constellations.Vel');
    case 'Vir':
      return i18n.t('constellations.Vir');
    case 'Vol':
      return i18n.t('constellations.Vol');
    case 'Vul':
      return i18n.t('constellations.Vul');
    default:
      return i18n.t('common.errors.unknown');
  }
};