export const weatherImages: any = {
  'default': require('../../../assets/icons/weather/default.png'),
  '01d': require('../../../assets/icons/weather/01d.png'),
  '01n': require('../../../assets/icons/weather/01n.png'),
  '02d': require('../../../assets/icons/weather/02d.png'),
  '02n': require('../../../assets/icons/weather/02n.png'),
  '03d': require('../../../assets/icons/weather/03d.png'),
  '03n': require('../../../assets/icons/weather/03n.png'),
  '04d': require('../../../assets/icons/weather/04d.png'),
  '04n': require('../../../assets/icons/weather/04n.png'),
  '09d': require('../../../assets/icons/weather/09d.png'),
  '09n': require('../../../assets/icons/weather/09n.png'),
  '10d': require('../../../assets/icons/weather/10d.png'),
  '10n': require('../../../assets/icons/weather/10n.png'),
  '11d': require('../../../assets/icons/weather/11d.png'),
  '11n': require('../../../assets/icons/weather/11n.png'),
  '13d': require('../../../assets/icons/weather/13d.png'),
  '13n': require('../../../assets/icons/weather/13n.png'),
  '50d': require('../../../assets/icons/weather/50d.png'),
  '50n': require('../../../assets/icons/weather/50n.png'),
}

export const astroImages: any = {
  'CL+N': require('../../../assets/icons/astro/CL+N.png'),
  'DRKN': require('../../../assets/icons/astro/DRKN.png'),
  'G': require('../../../assets/icons/astro/G.png'),
  'GCL': require('../../../assets/icons/astro/GCL.png'),
  'GGROUP': require('../../../assets/icons/astro/GGROUP.png'),
  'GPAIR': require('../../../assets/icons/astro/GPAIR.png'),
  'GTRPL': require('../../../assets/icons/astro/GTRPL.png'),
  'HII': require('../../../assets/icons/astro/HII.png'),
  'NEB': require('../../../assets/icons/astro/NEB.png'),
  'OCL': require('../../../assets/icons/astro/OCL.png'),
  'OTHER': require('../../../assets/icons/astro/OTHER.png'),
  'PN': require('../../../assets/icons/astro/PN.png'),
  'RFN': require('../../../assets/icons/astro/RFN.png'),
  'SNR': require('../../../assets/icons/astro/SNR.png'),
  '*': require('../../../assets/icons/astro/STAR.png'),
  '*ASS': require('../../../assets/icons/astro/STARASS.png'),
  '**': require('../../../assets/icons/astro/STARSTAR.png'),
  'SUN': require('../../../assets/icons/astro/planets/color/SUN.png'),
  'MERCURY': require('../../../assets/icons/astro/planets/color/MERCURY.png'),
  'VENUS': require('../../../assets/icons/astro/planets/color/VENUS.png'),
  'EARTH': require('../../../assets/icons/astro/planets/color/EARTH.png'),
  'MARS': require('../../../assets/icons/astro/planets/color/MARS.png'),
  'JUPITER': require('../../../assets/icons/astro/planets/color/JUPITER.png'),
  'SATURN': require('../../../assets/icons/astro/planets/color/SATURN.png'),
  'URANUS': require('../../../assets/icons/astro/planets/color/URANUS.png'),
  'NEPTUNE': require('../../../assets/icons/astro/planets/color/NEPTUNE.png'),
  'BRIGHTSTAR': require('../../../assets/icons/astro/BRIGHTSTAR.png'),
  'CONSTELLATION': require('../../../assets/icons/astro/constellations/TRIANGULUM AUSTRALE.png')
}

export const constellationsImages: any = {
  'And': require('../../../assets/icons/astro/constellations/ANDROMEDA.png'),
  'Aqr': require('../../../assets/icons/astro/constellations/AQUARIUS.png'),
  'Ara': require('../../../assets/icons/astro/constellations/ARA.png'),
  'Ari': require('../../../assets/icons/astro/constellations/ARIES.png'),
  'Aur': require('../../../assets/icons/astro/constellations/AURIGA.png'),
  'Boo': require('../../../assets/icons/astro/constellations/BOOTES.png'),
  'Cae': require('../../../assets/icons/astro/constellations/CAELUM.png'),
  'Cap': require('../../../assets/icons/astro/constellations/CAPRICORN.png'),
  'Car': require('../../../assets/icons/astro/constellations/CARINA.png'),
  'Cas': require('../../../assets/icons/astro/constellations/CASSIOPEIA.png'),
  'Cen': require('../../../assets/icons/astro/constellations/CENTARUS.png'),
  'Cep': require('../../../assets/icons/astro/constellations/CEPHEUS.png'),
  'Cet': require('../../../assets/icons/astro/constellations/CETUS.png'),
  'Cha': require('../../../assets/icons/astro/constellations/CHAMAELEON.png'),
  'Cir': require('../../../assets/icons/astro/constellations/CIRCINUS.png'),
  'CMa': require('../../../assets/icons/astro/constellations/CANIS MAJOR.png'),
  'CMi': require('../../../assets/icons/astro/constellations/CANIS MINOR.png'),
  'Cnc': require('../../../assets/icons/astro/constellations/CANCER.png'),
  'Col': require('../../../assets/icons/astro/constellations/COLUMBA.png'),
  'Com': require('../../../assets/icons/astro/constellations/COMA BERENICES.png'),
  'CrA': require('../../../assets/icons/astro/constellations/CORONA AUSTRALIS.png'),
  'CrB': require('../../../assets/icons/astro/constellations/CORONA BOREALIS.png'),
  'Crt': require('../../../assets/icons/astro/constellations/CRATER.png'),
  'Cru': require('../../../assets/icons/astro/constellations/CRUX.png'),
  'Crv': require('../../../assets/icons/astro/constellations/CORVUS.png'),
  'CVn': require('../../../assets/icons/astro/constellations/CANES VENATICI.png'),
  'Cyg': require('../../../assets/icons/astro/constellations/CYGNUS.png'),
  'Del': require('../../../assets/icons/astro/constellations/DELPHINUS.png'),
  'Dor': require('../../../assets/icons/astro/constellations/DORADO.png'),
  'Dra': require('../../../assets/icons/astro/constellations/DRACO.png'),
  'Equ': require('../../../assets/icons/astro/constellations/EQUULEUS.png'),
  'Eri': require('../../../assets/icons/astro/constellations/ERIDANUS.png'),
  'For': require('../../../assets/icons/astro/constellations/FORNAX.png'),
  'Gem': require('../../../assets/icons/astro/constellations/GEMINI.png'),
  'Gru': require('../../../assets/icons/astro/constellations/GRUS.png'),
  'Her': require('../../../assets/icons/astro/constellations/HERCULES.png'),
  'Hor': require('../../../assets/icons/astro/constellations/HOROLOGIUM.png'),
  'Hya': require('../../../assets/icons/astro/constellations/HYDRA.png'),
  'Hyi': require('../../../assets/icons/astro/constellations/HYDRUS.png'),
  'Ind': require('../../../assets/icons/astro/constellations/INDUS.png'),
  'Lac': require('../../../assets/icons/astro/constellations/LACERTA.png'),
  'Leo': require('../../../assets/icons/astro/constellations/LEO.png'),
  'Lep': require('../../../assets/icons/astro/constellations/LEPUS.png'),
  'Lib': require('../../../assets/icons/astro/constellations/LIBRA.png'),
  'LMi': require('../../../assets/icons/astro/constellations/LEO MINOR.png'),
  'Lup': require('../../../assets/icons/astro/constellations/LUPUS.png'),
  'Lyn': require('../../../assets/icons/astro/constellations/LYNX.png'),
  'Lyr': require('../../../assets/icons/astro/constellations/LYRA.png'),
  'Men': require('../../../assets/icons/astro/constellations/MENSA.png'),
  'Mic': require('../../../assets/icons/astro/constellations/MICROSCOPIUM.png'),
  'Mon': require('../../../assets/icons/astro/constellations/MONOCEROS.png'),
  'Mus': require('../../../assets/icons/astro/constellations/MUSCA.png'),
  'Nor': require('../../../assets/icons/astro/constellations/NORMA.png'),
  'Oct': require('../../../assets/icons/astro/constellations/OCTANS.png'),
  'Oph': require('../../../assets/icons/astro/constellations/OPHIUCHUS.png'),
  'Ori': require('../../../assets/icons/astro/constellations/ORION.png'),
  'Pav': require('../../../assets/icons/astro/constellations/PAVO.png'),
  'Peg': require('../../../assets/icons/astro/constellations/PEGASUS.png'),
  'Per': require('../../../assets/icons/astro/constellations/PERSEUS.png'),
  'Phe': require('../../../assets/icons/astro/constellations/PHOENIX.png'),
  'Pic': require('../../../assets/icons/astro/constellations/PICTOR.png'),
  'PsA': require('../../../assets/icons/astro/constellations/PISCIS AUSTRINUS.png'),
  'Psc': require('../../../assets/icons/astro/constellations/PISCES.png'),
  'Pup': require('../../../assets/icons/astro/constellations/PUPPIS.png'),
  'Pyx': require('../../../assets/icons/astro/constellations/PYXIS.png'),
  'Ret': require('../../../assets/icons/astro/constellations/RETICULUM.png'),
  'Scl': require('../../../assets/icons/astro/constellations/SCULPTOR.png'),
  'Sco': require('../../../assets/icons/astro/constellations/SCORPIUS.png'),
  'Sct': require('../../../assets/icons/astro/constellations/SCUTUM.png'),
  'Ser': require('../../../assets/icons/astro/constellations/SERPENS.png'),
  'Se1': require('../../../assets/icons/astro/constellations/SERPENS.png'),
  'Se2': require('../../../assets/icons/astro/constellations/SERPENS.png'),
  'Sex': require('../../../assets/icons/astro/constellations/SEXTANS.png'),
  'Sge': require('../../../assets/icons/astro/constellations/SAGITTA.png'),
  'Sgr': require('../../../assets/icons/astro/constellations/SAGITTARIUS.png'),
  'Tau': require('../../../assets/icons/astro/constellations/TAURUS.png'),
  'Tel': require('../../../assets/icons/astro/constellations/TELESCOPIUM.png'),
  'TrA': require('../../../assets/icons/astro/constellations/TRIANGULUM AUSTRALE.png'),
  'Tri': require('../../../assets/icons/astro/constellations/TRIANGULUM.png'),
  'Tuc': require('../../../assets/icons/astro/constellations/TUCANA.png'),
  'UMa': require('../../../assets/icons/astro/constellations/URSA MAJOR.png'),
  'UMi': require('../../../assets/icons/astro/constellations/URSA MINOR.png'),
  'Vel': require('../../../assets/icons/astro/constellations/VELA.png'),
  'Vir': require('../../../assets/icons/astro/constellations/VIRGO.png'),
  'Vol': require('../../../assets/icons/astro/constellations/VOLANS.png'),
  'Vul': require('../../../assets/icons/astro/constellations/VULPECULA.png'),
  'OTHER': require('../../../assets/icons/astro/OTHER.png'),
}

export const planetsImages: any = {
  'MERCURY': require('../../../assets/images/planets/mercury.jpg'),
  'VENUS': require('../../../assets/images/planets/venus.jpg'),
  'EARTH': require('../../../assets/images/planets/earth.jpg'),
  'MARS': require('../../../assets/images/planets/mars.jpg'),
  'JUPITER': require('../../../assets/images/planets/jupiter.jpg'),
  'SATURN': require('../../../assets/images/planets/saturn.jpg'),
  'URANUS': require('../../../assets/images/planets/uranus.jpg'),
  'NEPTUNE': require('../../../assets/images/planets/neptune.jpg'),
}

export const twilightBandsBackgrounds: any = {
  'Day': require('../../../assets/icons/astro/bands/DAY.png'),
  'Civil': require('../../../assets/icons/astro/bands/CIVIL.png'),
  'Nautical': require('../../../assets/icons/astro/bands/NAUTICAL.png'),
  'Astronomical': require('../../../assets/icons/astro/bands/ASTRONOMICAL.png'),
  'Night': require('../../../assets/icons/astro/bands/NIGHT.png'),
}

export const moonIcons: any = {
  'New': require('../../../assets/icons/astro/moon/New Moon.png'),
  'Waxing Crescent': require('../../../assets/icons/astro/moon/Waxing Crescent.png'),
  'First Quarter': require('../../../assets/icons/astro/moon/First Quarter.png'),
  'Waxing Gibbous': require('../../../assets/icons/astro/moon/Waxing Gibbous.png'),
  'Full': require('../../../assets/icons/astro/moon/Full Moon.png'),
  'Waning Gibbous': require('../../../assets/icons/astro/moon/Waning Gibbous.png'),
  'Last Quarter': require('../../../assets/icons/astro/moon/Last Quarter.png'),
  'Waning Crescent': require('../../../assets/icons/astro/moon/Waning Crescent.png'),
}

export const localizedWhiteLogo: any = {
  'fr': require('../../../assets/logos/fr/logo_white.png'),
  'en': require('../../../assets/logos/en/logo_white.png'),
}

export const localizedBlackLogo: any = {
  'fr': require('../../../assets/logos/fr/logo_black.png'),
  'en': require('../../../assets/logos/en/logo_black.png'),
}

export const localizedImagePlaceholders: any = {
  'fr': require('../../../assets/images/placeholders/fr/image.png'),
  'en': require('../../../assets/images/placeholders/en/image.png'),
}

export const localizedVideoPlaceholders: any = {
  'fr': require('../../../assets/images/placeholders/fr/video.png'),
  'en': require('../../../assets/images/placeholders/en/video.png'),
}

export const localizedForecastPlaceholders: any = {
  'fr': require('../../../assets/images/placeholders/fr/forecast.png'),
  'en': require('../../../assets/images/placeholders/en/forecast.png'),
}

export const localizedNoRocketImageSmall: any = {
  'fr': require('../../../assets/images/placeholders/fr/launchCardSmall.png'),
  'en': require('../../../assets/images/placeholders/en/launchCardSmall.png'),
}

export const localizedNoRocketImage: any = {
  'fr': 'https://i.postimg.cc/cCdLq2ZH/no-Rocket-Fr.png',
  'en': 'https://i.postimg.cc/Sx126S4G/no-Rocket-En.png',
}