import { app_colors } from "../helpers/constants";

export const markdownStyles = {
  body: {
    color: app_colors.white,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: "GilroyRegular",
  },
  paragraph: {
    color: app_colors.white,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: "GilroyRegular",
    marginTop: 12,
    marginBottom: 12,
  },
  heading1: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 28,
    lineHeight: 32,
    marginTop: 32,
    marginBottom: 12,
  },
  heading2: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 22,
    lineHeight: 28,
    marginTop: 28,
    marginBottom: 10,
  },
  heading3: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 20,
    lineHeight: 26,
    marginTop: 24,
    marginBottom: 8,
  },
  heading4: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 18,
    lineHeight: 24,
    marginTop: 22,
    marginBottom: 8,
  },
  heading5: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 16,
    lineHeight: 22,
    marginTop: 20,
    marginBottom: 6,
  },
  heading6: {
    fontFamily: "GilroyBlack",
    textTransform: "uppercase" as "uppercase",
    color: app_colors.white,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 18,
    marginBottom: 6,
  },
  blockquote: {
    fontFamily: "GilroyRegular",
    color: app_colors.white,
    backgroundColor: app_colors.white_no_opacity,
    borderRadius: 10,
    borderLeftWidth: 6,
    borderLeftColor: app_colors.white_sixty,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  bullet_list: {
    marginTop: 12,
    marginBottom: 12,
  },
  ordered_list: {
    marginTop: 12,
    marginBottom: 12,
  },
  list_item: {
    color: app_colors.white,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: "GilroyRegular",
  },
  strong: {
    fontFamily: "GilroyBlack",
    color: app_colors.white,
  },
  em: {
    fontFamily: "GilroyRegular",
    color: app_colors.white,
    fontStyle: "italic" as "italic",
  },
  code_inline: {
    backgroundColor: app_colors.white_no_opacity,
    color: app_colors.white,
    fontFamily: "DMMonoRegular",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  fence: {
    backgroundColor: app_colors.white_no_opacity,
    borderRadius: 10,
    padding: 10,
  },
  code_block: {
    color: app_colors.white,
    fontFamily: "DMMonoRegular",
    lineHeight: 22,
  },
  link: {
    color: app_colors.yellow,
    fontFamily: "GilroyBlack",
    textDecorationLine: "underline" as "underline",
  },
  table: {
    borderColor: app_colors.white,
  },
  td: {
    borderColor: app_colors.white,
  },
  tr: {
    borderColor: app_colors.white,
  },
  image: {
    width: "100%",
    height: 230,
    resizeMode: "contain" as "contain",
    marginVertical: 12,
    borderRadius: 12,
  },
}
