export const routes = {
  onboarding: { path: 'Onboarding', requirements: [] },
  tutorial: { path: 'Tutorial', requirements: [] },
  home: { path: 'Home', requirements: [] },
  settings: { path: 'Settings', requirements: [] },
  language: { path: 'LanguageSelection', requirements: [] },
  about: { path: 'About', requirements: [] },
  scopeAlignment: { path: 'ScopeAlignmentScreen ', requirements: [] },
  weather: { path: 'WeatherScreen', requirements: [] },
  moonPhases: { path: 'MoonPhasesScreen', requirements: [] },
  objectDetails: { path: 'ObjectDetails', requirements: [] },
  planetDetails: { path: 'PlanetDetails', requirements: [] },
  brightStarDetails: { path: 'BrightStarDetails', requirements: [] },
  solarWeather: { path: 'SolarWeatherScreen', requirements: [] },
  favoritesViewPoints: { path: 'FavoritesViewPoints', requirements: [] },
  apod: { path: 'ApodScreen', requirements: [] },
  skymapgenerator: { path: 'SkyMapGeneratorScreen', requirements: [] },
  satelliteTracker: { path: 'SatelliteTrackerScreen', requirements: [] },
  issTracker: { path: 'IssTrackerScreen', requirements: [] },
  starlinkTracker: { path: 'StarlinkTrackerScreen', requirements: [] },
  spaceXDataScreen: { path: 'SpaceXDataScreen', requirements: [] },
  favorites: { path: 'FavoritesScreen', requirements: [] },
  sellScreen: { path: 'SellScreen', requirements: [] },
  transitScreen: { path: 'TransitScreen', requirements: [] },
  astroDataInfos: { path: 'AstroDataInfos', requirements: [] },
  widgetsManager: {path: 'WidgetsManager', requirements: []},
  changelogScreen: {path: 'ChangelogScreen', requirements: []},
  launchesScreen: {path: 'LaunchesScreen', requirements: []}
}