export const routes = {
  onboarding: {path: 'Onboarding', requirements: []},
  home: { path: 'Home', requirements: [] },
  settings: { path: 'Settings', requirements: [] },
  about: { path: 'About', requirements: [] },
  scopeAlignment: { path: 'ScopeAlignmentScreen ', requirements: [] },
  weather: { path: 'WeatherScreen', requirements: [] },
  moonPhases: { path: 'MoonPhasesScreen', requirements: [] },
  objectDetails: { path: 'ObjectDetails', requirements: [] },
  solarWeather: { path: 'SolarWeatherScreen', requirements: [] },
  favoritesViewPoints: { path: 'FavoritesViewPoints', requirements: [] },
  apod: { path: 'ApodScreen', requirements: [] },
  skymapgenerator: { path: 'SkyMapGeneratorScreen', requirements: [] },
  satelliteTracker: {path: 'SatelliteTrackerScreen', requirements: []},
}