export const routes = {
  onboarding: { path: 'Onboarding', requirements: [] },
  tutorial: { path: 'Tutorial', requirements: [] },
  home: { path: 'Home', requirements: [] },
  settings: { path: 'Settings', requirements: [] },
  about: { path: 'About', requirements: [] },
  scopeAlignment: { path: 'ScopeAlignmentScreen ', requirements: [] },
  weather: { path: 'WeatherScreen', requirements: [] },
  moonPhases: { path: 'MoonPhasesScreen', requirements: [] },
  objectDetails: { path: 'ObjectDetails', requirements: [] },
  planetDetails: { path: 'PlanetDetails', requirements: [] },
  brightStarDetails: { path: 'BrightStarDetails', requirements: [] },
  solarWeather: { path: 'SolarWeatherScreen', requirements: [] },
  favoritesViewPoints: { path: 'FavoritesViewPoints', requirements: [] },
  apod: { path: 'ApodScreen', requirements: [] },
  skymapgenerator: { path: 'SkyMapGeneratorScreen', requirements: [] },
  satelliteTracker: { path: 'SatelliteTrackerScreen', requirements: [] },
  favorites: { path: 'FavoritesScreen', requirements: [] },
}