export const RENDER_ORDER = {
  background: -80,
  dso: -70,
  planets: -50,
  moon: -40,
  atmosphere: -30,
  stars: -20,
  azGrid: -10,
  eqGrid: -9,
  constellations: -5,
  ground: 11,
  selectionCircle: 12,
  labels: 15,
} as const;

export const LAYER_NAMES = {
  background: 'background',
  stars: 'stars',
  planets: 'planets',
  sun: 'sun',
  moon: 'moon',
  dso: 'dso',
  constellations: 'constellations',
  constellationLabels: 'constellationLabels',
  ground: 'ground',
  atmosphere: 'atmosphere',
  selectionCircle: 'selectionCircle',
  azGrid: 'azGrid',
  eqGrid: 'eqGrid',
  compassLabels: 'compassLabels',
} as const;
