export type DSO = {
  name: string;
  type: string;
  ra: string;
  dec: string;
  const: string;
  maj_ax: number | string;
  min_ax: number | string;
  pos_ang: number | string;
  b_mag: number | string;
  v_mag: number | string;
  j_mag: number | string;
  h_mag: number | string;
  k_mag: number | string;
  surf_br: number | string;
  hubble: string;
  pax: number | string;
  pm_ra: number | string;
  pm_dec: number | string;
  rad_vel: number | string;
  redshift: number | string;
  cstar_u_mag: number | string;
  cstar_b_mag: number | string;
  cstar_v_mag: number | string;
  m: number | string;
  ngc: number | string;
  ic: number | string;
  cstar_name: string;
  identifiers: string;
  common_names: string;
  ned_notes: string;
  open_ngc_notes: string;
  sources: string;
  image_url: string;
  distance: number | string;
  dist_unit: string;
  dimensions: string;
  discovered_by: string;
  discovery_year: string;
  apparent_size: string;
  age: number | string;
}